### ISSUE TITLE
Problem Maestro connection

### ISSUE THREAD

**Issue by firssty** [BenMoon/LabSoft#1]
Dear,

In first thank you very much for your script. I installed all package.  But when I execute PowerMeter.py or gentec.py and I clic on connect (IP is same and port as well) I have the following error : 

" runfile('C:/Users/kgaudfrin/Desktop/LabSoft-master/Instruments/gentec.py', wdir='C:/Users/kgaudfrin/Desktop/LabSoft-master/Instruments')
connected
Traceback (most recent call last):

  File "C:/Users/kgaudfrin/Desktop/LabSoft-master/Instruments/gentec.py", line 96, in connectMeter
    self.dataAq_worker.start.emit()

AttributeError: 'MaestroUi' object has no attribute 'dataAq_worker'

0
0

"

I don't know how to fix the problem I tried to uncomment in gentec.py
(line 15)
#from Helpers.genericthread import GenericWorker

and (line 84 to 89)
#thread for getting data from socket
#self.updateAvgTxt.connect(self.__updateAvgTxt)
#self.dataAq_Thr = QThread()
#self.dataAq_Thr.start()        self.dataAq_worker = GenericWorker(self.__getData)       #self.dataAq_worker.moveToThread(self.dataAq_Thr)

But the problem is not solve and nothing appear on the graph.

Kévin

**Comment by BenMoon** [comment]
Dear Kevin,
this script is many years old and I don't have the required hardware anylonger. Sorry.
Maybe you start trying to talk to your Gentec using Putty just to make sure that this connection works.

Best
